### ISSUE TITLE
CDN assets down

### ISSUE THREAD

**Issue by dnordberg** [amiechen/stitches-template-generator#4]
CDN assets are down so the demo site and package don't currently work.

Error is:

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>7964C40632C51FF1</RequestId>
<HostId>
AB+7ABDEyVgqxvXuJyjNrClZ9WIU2N5jYhsRo8Uea+K5qWopfpt1mEOk2lyPbKRr0yfd2GzzO0o=
</HostId>
</Error>
```

**Comment by dnordberg** [comment]
Error is:

`<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>7964C40632C51FF1</RequestId>
<HostId>
AB+7ABDEyVgqxvXuJyjNrClZ9WIU2N5jYhsRo8Uea+K5qWopfpt1mEOk2lyPbKRr0yfd2GzzO0o=
</HostId>
</Error>`

**Comment by amiechen** [comment]
fixed. Thanks!
